name: Check Redis URL Secret

on:
  push:
    branches:
      - main

jobs:
  check-redis-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: View Redis URL Secret
        run: |
          python -c "import subprocess; subprocess.run(['gh', 'auth', 'login', '--with-token'], check=True)"
          python -c "import subprocess; subprocess.run(['gh', 'secret', 'view', 'REDIS_URL', '--repo', 'imdb_recommender'], check=True)"
