name: Get Redis URL

on:
  push:
    branches:
      - main

jobs:
  redis-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Redis URL and run script
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: python3 imdb_recommender/imdb250_deployment/imdb250_data/imdb250_data.py
