name: Redis URL

on:
  push:
    branches:
    - main
jobs:
  get-redis-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Display Redis URL from secret
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: 
          echo "Environment variable REDIS_URL is set."
