name: Redis URL

on:
  push:
    branches:
      - main

jobs:
  redis-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Redis URL from secret
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: echo "REDIS_URL: $REDIS_URL"
