name: Redis URL

on:
  push:
    branches:
      - main

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Redis URL from secret
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: 
          echo "Environment variable REDIS_URL is set."
          python print_/print_.py
